### ISSUE TITLE
webiny An error occurred during deployment of pageBuilderInstallation

### ISSUE THREAD

**Issue by ValiDraganescu** [webiny/webiny-js#1043]
I try to deploy the local environment for api. I get an Access Denied error

## This is:
- Bug

## Specifications

  - version:  cli 4.1.0
  - OS: macOS
  - Browser: Chrome

## Expected Behavior
The api should deploy to AWS

## Actual Behavior
I get this error
```
webiny:i18nGraphQL Building 'i18nGraphQL' +0ms
  webiny:i18nGraphQL Finished building 'i18nGraphQL' +4s
  webiny:i18nGraphQL Starting deployment of lambda '83853007_..._api_local_i18nGraphQL' to the 'eu-west-1' region. +2ms
  webiny:i18nGraphQL Packaging lambda code from './i18n/graphql/build' +0ms
  webiny:i18nGraphQL Updating '83853007_..._api_local_i18nGraphQL' lambda config. +679ms
  webiny:i18nGraphQL Successfully deployed lambda '83853007_..._api_local_i18nGraphQL' in the 'eu-west-1' region. +406ms
  webiny Tracking component: @webiny/serverless-function (deploy) +6s
  webiny:pageBuilderInstallation Creating archive from '@webiny/api-page-builder/installation' and uploading to '83853007-...-files/page-builder-installation.zip' +0ms
  webiny An error occurred during deployment of pageBuilderInstallation +1s
AccessDenied: Access Denied
    at Request.extractError (/Users/.../node_modules/aws-sdk/lib/services/s3.js:831:35)
    at Request.callListeners (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/.../node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/.../node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/.../node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/.../node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/.../node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2020-06-20T15:08:48.925Z,
  requestId: '8F72A2C1DF30A38D',
  extendedRequestId: 'MC7vpxNMXEF345+bQYW53wpol7CRTipL3YM7x/R/IjPyR+YSshROy7tCCPqj2l6/pNFk10m01Qs=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 49.20177683416329
}
error Command failed with exit code 1.

```
## Steps to Reproduce the Problem
1. follow the tutorial here  [https://docs.webiny.com/docs/get-started/quick-start](https://docs.webiny.com/docs/get-started/quick-start)

## Detailed Description
My serverless profile has the credentials of an AWS user with administrator access (although I hate to have this kind of users)
## Possible solution
Add a more detailed log that actually says what AWS cli command was used or what is the service that returns the error. This way I can work my way into having an AWS user with minimal permissions.

**Comment by Pavel910** [comment]
@ValiDraganescu That error is usually caused by S3, we've seen it a couple of times, but never managed to figure out the exact cause. It has something to do with S3 buckets removal/creation, but it's very hard to replicate reliably. Usually we just rename the `S3_BUCKET` variable in `api/.env.json` and deploy the `api` stack again.

Regarding `Full Admin` access, we know it's not nice, but so far we don't have an exact list of policies required for deployment of all resources. We'll get to that some time in the future, and also maybe the community gets more involved and helps us out with that.

We have some beginnings of that in this community thread: https://community.webiny.com/t/aws-user-with-minimal-permissions-to-deploy-webiny-and-automated-deployment-question/145

**Comment by ValiDraganescu** [comment]
@Pavel910 
After I change the bucket name I still don't get a successful deployment, see full output bellow
```
yarn webiny deploy api --env=local
yarn run v1.19.1
$ /Users/.../node_modules/.bin/webiny deploy api --env=local
  This is the first deploy of local environment, so it may take a few minutes.
  💡 Loaded local environment from <projectRoot>/.env.json.
  💡 Loaded local environment from <projectRoot>/api/.env.json.

  ✔ Great! Your MongoDB is accessible.

  webiny Loaded user ID: d4e10a82-58e7-471e-ad3b-4a75696fe386 +0ms
  webiny Tracking is ENABLED +0ms
  webiny Collecting components from the template. +651ms
  webiny Executing the template's components graph. +19ms
  webiny:lambdaRole Creating role 'qu65gl_...-landing_api_local_lambdaRole'. +0ms
  webiny:lambdaRole Role 'qu65gl_...-landing_api_local_lambdaRole' was successfully deployed to region 'eu-west-1'. +6s
  webiny Tracking component: @webiny/serverless-aws-iam-role (deploy) +6s
  webiny:cognito Creating new user pool. +0ms
  webiny:cognito Created user pool 'eu-west-1_6a1JOWeEh'. +937ms
  webiny:cognito Creating new user pool client. +0ms
  webiny Tracking component: @webiny/serverless-aws-cognito-user-pool (deploy) +2s
  webiny:databaseProxy Building 'databaseProxy' +0ms
  webiny:databaseProxy Finished building 'databaseProxy' +4s
  webiny:databaseProxy Starting deployment of lambda 'qu65gl_...-landing_api_local_databaseProxy' to the 'eu-west-1' region. +186ms
  webiny:databaseProxy Packaging lambda code from './databaseProxy/build' +4ms
  webiny:databaseProxy Updating 'qu65gl_...-landing_api_local_databaseProxy' lambda config. +622ms
  webiny:databaseProxy Successfully deployed lambda 'qu65gl_...-landing_api_local_databaseProxy' in the 'eu-west-1' region. +364ms
  webiny:databaseProxy Setting function's concurrency limit to 15. +26ms
  webiny Tracking component: @webiny/serverless-function (deploy) +6s
  webiny:imageTransformer Building 'imageTransformer' +0ms
  webiny:imageTransformer Finished building 'imageTransformer' +2s
  webiny:imageTransformer Starting deployment of lambda 'qu65gl_...-landing_api_local_imageTransformer' to the 'eu-west-1' region. +1ms
  webiny:imageTransformer Packaging lambda code from './files/transform/build' +0ms
  webiny:imageTransformer Updating 'qu65gl_...-landing_api_local_imageTransformer' lambda config. +423ms
  webiny:imageTransformer Successfully deployed lambda 'qu65gl_...-landing_api_local_imageTransformer' in the 'eu-west-1' region. +385ms
  webiny Tracking component: @webiny/serverless-function (deploy) +4s
  webiny:filesManage Building 'filesManage' +0ms
  webiny:filesManage Finished building 'filesManage' +3s
  webiny:filesManage Starting deployment of lambda 'qu65gl_...-landing_api_local_filesManage' to the 'eu-west-1' region. +1ms
  webiny:filesManage Packaging lambda code from './files/manage/build' +1ms
  webiny:filesManage Updating 'qu65gl_...-landing_api_local_filesManage' lambda config. +460ms
  webiny:filesManage Adding 'lambda:InvokeFunction' permission to 'qu65gl_...-landing_api_local_filesManage' +374ms
  webiny:filesManage Successfully deployed lambda 'qu65gl_...-landing_api_local_filesManage' in the 'eu-west-1' region. +2ms
  webiny Tracking component: @webiny/serverless-function (deploy) +4s
(node:9103) UnhandledPromiseRejectionWarning: ResourceConflictException: The statement id (s3invoke) provided already exists. Please provide a new statement id, or remove the existing statement.
    at Object.extractError (/Users/.../node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/.../node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/.../node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/.../node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/.../node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/.../node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/.../node_modules/aws-sdk/lib/request.js:690:12)
(node:9103) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9103) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  webiny:settingsManager Building 'settingsManager' +0ms
  webiny:settingsManager Finished building 'settingsManager' +4s
  webiny:settingsManager Starting deployment of lambda 'qu65gl_...-landing_api_local_settingsManager' to the 'eu-west-1' region. +1ms
  webiny:settingsManager Packaging lambda code from './settingsManager/build' +0ms
  webiny:settingsManager Updating 'qu65gl_...-landing_api_local_settingsManager' lambda config. +526ms
  webiny:settingsManager Successfully deployed lambda 'qu65gl_...-landing_api_local_settingsManager' in the 'eu-west-1' region. +442ms
  webiny Tracking component: @webiny/serverless-function (deploy) +6s
  webiny:securityValidateAccessToken Building 'securityValidateAccessToken' +0ms
  webiny:securityValidateAccessToken Finished building 'securityValidateAccessToken' +5s
  webiny:securityValidateAccessToken Starting deployment of lambda 'qu65gl_...-landing_api_local_securityValidateAccessToken' to the 'eu-west-1' region. +1ms
  webiny:securityValidateAccessToken Packaging lambda code from './security/validateAccessToken/build' +0ms
  webiny:securityValidateAccessToken Updating 'qu65gl_...-landing_api_local_securityValidateAccessToken' lambda config. +527ms
  webiny:securityValidateAccessToken Successfully deployed lambda 'qu65gl_...-landing_api_local_securityValidateAccessToken' in the 'eu-west-1' region. +368ms
  webiny Tracking component: @webiny/serverless-function (deploy) +6s
  webiny:filesDownload Building 'filesDownload' +0ms
  webiny:filesDownload Finished building 'filesDownload' +3s
  webiny:filesDownload Starting deployment of lambda 'qu65gl_...-landing_api_local_filesDownload' to the 'eu-west-1' region. +1ms
  webiny:filesDownload Packaging lambda code from './files/download/build' +0ms
  webiny:filesDownload Updating 'qu65gl_...-landing_api_local_filesDownload' lambda config. +351ms
  webiny:filesDownload Successfully deployed lambda 'qu65gl_...-landing_api_local_filesDownload' in the 'eu-west-1' region. +390ms
  webiny Tracking component: @webiny/serverless-function (deploy) +4s
  webiny:filesBucket Deploying bucket '...-landing-files-2' in region 'eu-west-1' +0ms
  webiny:filesBucket Checking if bucket ...-landing-files-2 exists. +14ms
  webiny:filesBucket Bucket ...-landing-files-2 does not exist. Creating... +484ms
  webiny:filesBucket Bucket ...-landing-files-2 created. Confirming it's ready... +1s
  webiny:filesBucket Bucket ...-landing-files-2 creation confirmed. +411ms
  webiny:filesBucket Setting CORS for bucket '...-landing-files-2' +1ms
  webiny:filesBucket Setting notification configuration for bucket '...-landing-files-2' +761ms
InvalidArgument: Unable to validate the following destination configurations
    at Request.extractError (/Users/.../node_modules/aws-sdk/lib/services/s3.js:831:35)
    at Request.callListeners (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/.../node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/.../node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/.../node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/.../node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/.../node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Unable to validate the following destination configurations',
  code: 'InvalidArgument',
  region: null,
  time: 2020-06-20T22:45:57.395Z,
  requestId: '9C4E4A32E503184B',
  extendedRequestId: 'bMAkBrVNTXbJAZStudC2lcSXis/+PnTOoCS0XHDZ9bv21KmpcqBC/vhBGeDj5ywskkTh/nwaSF8=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 83.187670923577,
  attemptNumber: 4,
  retriesLeft: 0
}
  ...-landing-files-2 {
  LambdaFunctionConfigurations: [
    {
      LambdaFunctionArn: 'arn:aws:lambda:eu-west-1:575598817587:function:qu65gl_...-landing_api_local_filesManage',
      Events: [Array]
    }
  ]
}
  webiny An error occurred during deployment of filesBucket +13s
InvalidArgument: Unable to validate the following destination configurations
    at Request.extractError (/Users/.../node_modules/aws-sdk/lib/services/s3.js:831:35)
    at Request.callListeners (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/.../node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/.../node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/.../node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/.../node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/.../node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/.../node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Unable to validate the following destination configurations',
  code: 'InvalidArgument',
  region: null,
  time: 2020-06-20T22:45:57.395Z,
  requestId: '9C4E4A32E503184B',
  extendedRequestId: 'bMAkBrVNTXbJAZStudC2lcSXis/+PnTOoCS0XHDZ9bv21KmpcqBC/vhBGeDj5ywskkTh/nwaSF8=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 83.187670923577,
  attemptNumber: 4,
  retriesLeft: 0
}
error Command failed with exit code 1.
```

**Comment by Pavel910** [comment]
@ValiDraganescu this exact series of errors is something we were trying to debug with another community member on Slack the other day. So annoying, and still not sure what's the root cuase.

Anyhow, the error you're getting now 

```
ResourceConflictException: The statement id (s3invoke) provided already exists. Please provide a new statement id, or remove the existing statement.
```
is referring to this: `api/resources.js:225`

![image](https://user-images.githubusercontent.com/3920893/85219224-5035d300-b3a2-11ea-8655-679504dc9e82.png)
Basically, we're trying to allow an S3 bucket to invoke this `filesManage` lambda. Since you already had this permission deployed to tour previous bucket, you need to rename the `StatementId` to something unique.

Just add a letter or rename it completely, it doesn't matter. It just must be a unique string.
Hopefully this will help.

**Comment by ValiDraganescu** [comment]
Is there a way to get more verbose AWS error messages?

**Comment by ValiDraganescu** [comment]
In my first code snippet, the error says `region: null,` could this be the issue?

**Comment by Pavel910** [comment]
Unfortunately not. The messages you see are exactly what we get from AWS SDK. We don't wrap or transform them in any way.

I don't think `region: null` is the problem, because if you didn't have a region, you wouldn't be able to deploy any of the resources.

**Comment by Pavel910** [comment]
Let me try deploying to `eu-west-1` region. We'll see how it goes.

**Comment by ValiDraganescu** [comment]
Can I reach you over a chat somewhere? Maybe we figure this out

**Comment by Pavel910** [comment]
Sure, jump over to https://www.webiny.com/slack/
