### ISSUE TITLE
npx create-webiny-project: 'rm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by DerikDau** [webiny/webiny-js#1086]
## This is:
- Bug:
C:\Users\derik\source\repos\bol3_builder>npx create-webiny-project bol3_builder --log
npx: installed 216 in 10.806s
  Creating project at C:\Users\derik\source\repos\bol3_builder\bol3_builder:
  √ Pre-template setup
  √ Install template package
  √ Create project folders
  × Set up project dependencies
    → operable program or batch file.
    Initialize git
    Get proper package versions
    Resolve packages
    Install dependencies
    Run template-specific actions
Unable to complete project initialization Error: Command failed with exit code 1: rm C:\Users\derik\source\repos\bol3_builder\bol3_builder\dependencies.json
'rm' is not recognized as an internal or external command,
operable program or batch file.
    at makeError (C:\Users\derik\AppData\Roaming\npm-cache\_npx\25060\node_modules\create-webiny-project\node_modules\execa\lib\error.js:59:11)
    at Function.module.exports.sync (C:\Users\derik\AppData\Roaming\npm-cache\_npx\25060\node_modules\create-webiny-project\node_modules\execa\index.js:188:17)
    at Task.task (C:\Users\derik\AppData\Roaming\npm-cache\_npx\25060\node_modules\create-webiny-project\init.js:81:23)
    at C:\Users\derik\AppData\Roaming\npm-cache\_npx\25060\node_modules\create-webiny-project\node_modules\listr\lib\task.js:167:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  shortMessage: 'Command failed with exit code 1: rm C:\\Users\\derik\\source\\repos\\bol3_builder\\bol3_builder\\dependencies.json',
  command: 'rm C:\\Users\\derik\\source\\repos\\bol3_builder\\bol3_builder\\dependencies.json',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "'rm' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  context: [Object: null prototype] {}
}

- version: 
yarn --version
1.22.0
node --version
v12.18.1
- OS: Windows 10

**Comment by DerikDau** [comment]
I got its working on Git bash.
