### ISSUE TITLE
webiny:api build failes during deployment - Quickstart

### ISSUE THREAD

**Issue by sherlockholmes** [webiny/webiny-js#1256]
## This is:
- Bug

## Specifications

  - Version: 4.12
  - OS: Amazon Linux AMI 2018.03(Cloud9)
  - Browser: Chrome
  - Node Version:  v10.20.1
  -  Yarn Version: 1.22.5

## Expected Behavior
The build of the api should be successfull following the Quick start guide.

## Actual Behavior
I tried to deploy a new fresh  version of webiny on my AWS environment following the Quickstart guide, but when I launch  the command.

yarn webiny deploy api --env=default

I got the following issue: 

raulhugo:~/environment/new-project (master) $ yarn webiny deploy api --env=default
yarn run v1.22.5
$ /home/ec2-user/environment/new-project/node_modules/.bin/webiny deploy api --env=default
  This is the first deploy of default environment, so it may take a few minutes.
   Loaded default environment from <projectRoot>/.env.json.
   Loaded default environment from <projectRoot>/api/.env.json.

  ✔ Great! Your MongoDB is accessible.

  webiny Collecting components from the template. +0ms
  webiny Executing the template's components graph. +12ms
{ InvalidArgument: Unable to validate the following destination configurations
    at Request.extractError (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/services/s3.js:837:35)
    at Request.callListeners (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message:
   'Unable to validate the following destination configurations',
  code: 'InvalidArgument',
  region: null,
  time: 2020-09-20T16:21:00.705Z,
  requestId: 'E1D55B882C815B72',
  extendedRequestId:
   'eHUf328LQjXOmGdgrDdEFIVBgX7pdcOjYEJP6pA72uUgvZK7V9Cb1o6CdjgJhsbxKbq7+6OIiw0=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 28.21956664932559,
  attemptNumber: 4,
  retriesLeft: 0 }
  3cd99212-vd0bezf { LambdaFunctionConfigurations:
   [ { LambdaFunctionArn:
        'arn:aws:lambda:us-west-2:757263354004:function:3cd99212_new-project_api_default_filesManage',
       Events: [Array] } ] }
  webiny An error occurred during deployment of filesBucket +31s
{ InvalidArgument: Unable to validate the following destination configurations
    at Request.extractError (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/services/s3.js:837:35)
    at Request.callListeners (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/ec2-user/environment/new-project/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message:
   'Unable to validate the following destination configurations',
  code: 'InvalidArgument',
  region: null,
  time: 2020-09-20T16:21:00.705Z,
  requestId: 'E1D55B882C815B72',
  extendedRequestId:
   'eHUf328LQjXOmGdgrDdEFIVBgX7pdcOjYEJP6pA72uUgvZK7V9Cb1o6CdjgJhsbxKbq7+6OIiw0=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 28.21956664932559,
  attemptNumber: 4,
  retriesLeft: 0 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Steps to Reproduce the Problem
1. Launch a Cloud9 Environment with AMI Linux Amazon Linux AMI 2018.03
2. Follow the QuickStart Guide

**Comment by chrisands** [comment]
Had the same error. For me it helped to setup `~/api/.env.json` file
```json
  "default": {
    "GRAPHQL_INTROSPECTION": true,
    "GRAPHQL_PLAYGROUND": true
  },
  "local": {
    "JWT_SECRET": "<here insert any jwt secret you will generate>",
    "S3_BUCKET": "<here insert s3 bucket name which will be created>"
  }
}
```

**Comment by jdpaterson** [comment]
Instead of `yarn webiny deploy api --env=default` use `yarn webiny deploy api --env=local`
