### ISSUE TITLE
Creating a new webiny project on Windows 10

### ISSUE THREAD

**Issue by compositeFlows** [webiny/webiny-js#1351]
Run: 
npx create-webiny-project project-two

## This is:
- Bug

## Specifications
  - version: node 15.5.0, npm 7.3.0, yarn 1.22.10
  - OS: Windows 10
  - Browser: Chrome

## Expected Behavior
Should create a new project called project-two

## Actual Behavior
Fails producing this error:
npx create-webiny-project project-two
  Creating project at C:/facemunch/webiny/project-two:
  √ Pre-template setup
  √ Install template package
  √ Create project folders
  √ Set up project dependencies
  √ Initialize git
  √ Get proper package versions
  √ Resolve packages
  × Install dependencies
    → info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    Run template-specific actions

    ERROR OUTPUT:
    ----------------------------------------
    Unable to install the necessary packages: Command failed with exit code 1: yarn
    warning @webiny/cli > debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
    warning @webiny/cli-plugin-deploy-components > debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
    warning @webiny/cli-plugin-deploy-components > chokidar > fsevents@2.1.3: Please update to v 2.2.x
    warning @webiny/project-utils > eslint-loader@3.0.2: This loader has been deprecated. Please use eslint-webpack-plugin
    warning @webiny/project-utils > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
    warning @webiny/project-utils > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
    warning @webiny/project-utils > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    warning @webiny/project-utils > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    warning @webiny/project-utils > react-native-web > deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
    warning @webiny/project-utils > react-native-web > fbjs > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
    warning @webiny/project-utils > node-sass > request > har-validator@5.1.5: this library is no longer supported
    warning @webiny/project-utils > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
    warning @webiny/project-utils > react-dev-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    warning @webiny/project-utils > react-dev-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    warning @webiny/project-utils > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    warning @webiny/project-utils > @webiny/app > @webiny/ui > rc-tooltip > babel-runtime > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
    warning @webiny/project-utils > @webiny/app > @webiny/ui > react-ace > @babel/polyfill@7.12.1: �  This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
    warning @webiny/project-utils > @webiny/app > @webiny/ui > react-ace > @babel/polyfill > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
    warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
    warning lerna > @lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    warning lerna > @lerna/bootstrap > @lerna/symlink-binary > @lerna/create-symlink > @zkochan/cmd-shim > mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
    warning workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-page-builder > @webiny/api-page-builder > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    warning workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-files-graphql > @webiny/api-files > @shelf/jest-mongodb > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
    warning workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-form-builder > @webiny/api-i18n > i18n-locales@0.0.2: Please upgrade to v0.0.3+ as we have fixed missing ISO-639-1 codes
    warning workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-security-graphql > @webiny/api-plugin-security-cognito > request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
    warning workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-page-builder > react-images@0.5.19: This beta version is no longer supported. Please update to 1.1.0-beta.4
    warning workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-page-builder > slate-react > memoize-one@4.1.0: New custom equality api does not play well with all equality helpers. Please use v5.x
    warning workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > admin > @webiny/app-template-admin-full > @webiny/app-template-admin > @webiny/app-plugin-security-cognito > @aws-amplify/auth > amazon-cognito-identity-js > buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
    warning workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > admin > @webiny/app-template-admin-full > @webiny/app-template-admin > @webiny/app-plugin-security-cognito > @aws-amplify/auth > @aws-amplify/core > aws-sdk > buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
    warning " > @babel/plugin-proposal-class-properties@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
    warning " > @babel/preset-env@7.12.11" has unmet peer dependency "@babel/core@^7.0.0-0".
    warning "@webiny/project-utils > apollo-cache-inmemory@1.6.6" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "@webiny/project-utils > apollo-client@2.6.10" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "@webiny/project-utils > apollo-link@1.2.14" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "@webiny/project-utils > apollo-link-http@1.5.17" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "@webiny/project-utils > react-apollo@3.1.5" has unmet peer dependency "graphql@^14.3.1".
    warning " > @babel/plugin-proposal-object-rest-spread@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
    warning "@babel/preset-typescript > @babel/plugin-transform-typescript@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
    warning "@webiny/project-utils > apollo-cache-inmemory > apollo-cache@1.3.5" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "@webiny/project-utils > @apollo/react-ssr > @apollo/react-hooks@3.1.5" has unmet peer dependency "graphql@^14.3.1".
    warning "@webiny/project-utils > apollo-cache-inmemory > apollo-utilities@1.3.4" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "@webiny/project-utils > @apollo/react-ssr > @apollo/react-common@3.1.4" has unmet peer dependency "apollo-utilities@^1.3.2".
    warning "@webiny/project-utils > @apollo/react-ssr > @apollo/react-common@3.1.4" has unmet peer dependency "graphql@^14.3.1".
    warning "@webiny/project-utils > apollo-link-http > apollo-link-http-common@0.2.16" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "@webiny/project-utils > react-apollo > @apollo/react-hoc@3.1.5" has unmet peer dependency "graphql@^14.3.1".
    warning "@webiny/project-utils > react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "apollo-cache@^1.3.2".
    warning "@webiny/project-utils > react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "apollo-utilities@^1.3.2".
    warning "@webiny/project-utils > react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "graphql@^14.3.1".
    warning " > @babel/cli@7.12.10" has unmet peer dependency "@babel/core@^7.0.0-0".
    warning " > @babel/plugin-proposal-throw-expressions@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
    warning "@babel/plugin-proposal-throw-expressions > @babel/plugin-syntax-throw-expressions@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
    warning " > @babel/plugin-transform-runtime@7.12.10" has unmet peer dependency "@babel/core@^7.0.0-0".
    warning " > @babel/preset-typescript@7.12.7" has unmet peer dependency "@babel/core@^7.0.0-0".
    warning " > eslint-import-resolver-babel-module@5.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
    warning " > eslint-import-resolver-babel-module@5.2.0" has unmet peer dependency "babel-plugin-module-resolver@^3.0.0 || ^4.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-security-graphql > @webiny/api-plugin-security-cognito > request-promise > request-promise-core@1.1.4" has unmet peer dependency "request@^2.34".
    warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.2" has unmet peer dependency "@octokit/core@>=3".
    warning " > ts-jest@26.4.4" has incorrect peer dependency "typescript@>=3.8 <5.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-page-builder > @webiny/api-cookie-policy@4.14.0" has unmet peer dependency "@webiny/graphql@^4.0.0-beta.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-page-builder > @webiny/api-google-tag-manager@4.14.0" has unmet peer dependency "@webiny/graphql@^4.0.0-beta.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > apollo-link-batch-http@1.2.14" has unmet peer dependency "graphql@^0.11.0 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-google-tag-manager@4.14.0" has unmet peer dependency "graphql-tag@^2.10.1".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-mailchimp@4.14.0" has unmet peer dependency "graphql-tag@^2.10.1".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-page-builder-theme > graphql-tag@2.10.1" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda@2.15.1" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > @apollo/gateway@0.14.1" has unmet peer dependency "graphql@^14.2.1 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-files-graphql > @webiny/api-files > @shelf/jest-mongodb@1.2.3" has unmet peer dependency "mongodb@3.x.x".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > @apollo/gateway > @apollo/federation@0.14.1" has unmet peer dependency "graphql@^14.0.2 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > graphql-tools@4.0.8" has unmet peer dependency "graphql@^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-security-graphql > @webiny/api-plugin-security-cognito > request-promise@4.2.6" has unmet peer dependency "request@^2.34".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > admin > @webiny/app-template-admin-full > @webiny/app-file-manager@4.14.0" has unmet peer dependency "graphql-tag@^2.10.1".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > admin > @webiny/app-template-admin-full > @webiny/app-file-manager@4.14.0" has unmet peer dependency "react-apollo@^3.1.3".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-files-graphql > @webiny/api-security > @webiny/graphql > graphql-type-long@0.1.1" has incorrect peer dependency "graphql@^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-form-builder > react-redux@7.2.2" has unmet peer dependency "redux@^2.0.0 || ^3.0.0 || ^4.0.0-0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-form-builder > timeago-react@2.0.1" has unmet peer dependency "prop-types@^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-form-builder > react-sortable-hoc@1.11.0" has unmet peer dependency "prop-types@^15.5.7".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-page-builder > react-sortable-tree@2.8.0" has incorrect peer dependency "react-dnd@^7.3.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-core@2.19.1" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-core > apollo-graphql@0.6.0" has unmet peer dependency "graphql@^14.2.1 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-types@0.5.1" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > @apollo/gateway > apollo-server-types@0.3.1" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-core > apollo-server-types@0.6.2" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-page-builder-theme > react-hamburger-menu@1.2.1" has unmet peer dependency "prop-types@>=15.5.7".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > @apollo/gateway > graphql-extensions@0.11.1" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-core > graphql-extensions@0.12.7" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > site > @webiny/app-template-site > @webiny/app-page-builder > react-sortable-tree > frontend-collective-react-dnd-scrollzone@1.0.2" has incorrect peer dependency "react-dnd@^7.3.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-core > apollo-cache-control@0.11.5" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-core > apollo-server-errors@2.4.2" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-core > apollo-server-plugin-base@0.10.3" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-core > apollo-tracing@0.12.1" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-core > graphql-upload@8.1.0" has unmet peer dependency "graphql@0.13.1 - 14".
    warning "workspace-aggregator-bf651f3b-5ea6-4aa3-91e0-525fd7edac83 > api-apollo-gateway > @webiny/handler-apollo-gateway > apollo-server-lambda > apollo-server-core > subscriptions-transport-ws@0.9.18" has unmet peer dependency "graphql@>=0.10.0".
    error C:\facemunch\webiny\project-two\node_modules\node-sass: Command failed.
    Exit code: 1
    Command: node scripts/build.js
    Arguments:
    Directory: C:\facemunch\webiny\project-two\node_modules\node-sass
    Output:
    Building: C:\Program Files\nodejs\node.exe C:\facemunch\webiny\project-two\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
    gyp info it worked if it ends with ok
    gyp verb cli [
    gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
    gyp verb cli   'C:\\facemunch\\webiny\\project-two\\node_modules\\node-gyp\\bin\\node-gyp.js',
    gyp verb cli   'rebuild',
    gyp verb cli   '--verbose',
    gyp verb cli   '--libsass_ext=',
    gyp verb cli   '--libsass_cflags=',
    gyp verb cli   '--libsass_ldflags=',
    gyp verb cli   '--libsass_library='
    gyp verb cli ]
    gyp info using node-gyp@3.8.0
    gyp info using node@15.5.0 | win32 | x64
    gyp verb command rebuild []
    gyp verb command clean []
    gyp verb clean removing "build" directory
    gyp verb command configure []
    gyp verb check python checking for Python executable "python2" in the PATH
    gyp verb `which` failed Error: not found: python2
    gyp verb `which` failed     at getNotFoundError (C:\facemunch\webiny\project-two\node_modules\which\which.js:13:12)
    gyp verb `which` failed     at F (C:\facemunch\webiny\project-two\node_modules\which\which.js:68:19)
    gyp verb `which` failed     at E (C:\facemunch\webiny\project-two\node_modules\which\which.js:80:29)
    gyp verb `which` failed     at C:\facemunch\webiny\project-two\node_modules\which\which.js:89:16
    gyp verb `which` failed     at C:\facemunch\webiny\project-two\node_modules\isexe\index.js:42:5
    gyp verb `which` failed     at C:\facemunch\webiny\project-two\node_modules\isexe\windows.js:36:5
    gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21)
    gyp verb `which` failed  python2 Error: not found: python2
    gyp verb `which` failed     at getNotFoundError (C:\facemunch\webiny\project-two\node_modules\which\which.js:13:12)
    gyp verb `which` failed     at F (C:\facemunch\webiny\project-two\node_modules\which\which.js:68:19)
    gyp verb `which` failed     at E (C:\facemunch\webiny\project-two\node_modules\which\which.js:80:29)
    gyp verb `which` failed     at C:\facemunch\webiny\project-two\node_modules\which\which.js:89:16
    gyp verb `which` failed     at C:\facemunch\webiny\project-two\node_modules\isexe\index.js:42:5
    gyp verb `which` failed     at C:\facemunch\webiny\project-two\node_modules\isexe\windows.js:36:5
    gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21) {
    gyp verb `which` failed   code: 'ENOENT'
    gyp verb `which` failed }
    gyp verb check python checking for Python executable "python" in the PATH
    gyp verb `which` succeeded python C:\Python39\python.EXE
    gyp ERR! configure error
    gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
    gyp ERR! stack   File "<string>", line 1
    gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
    gyp ERR! stack                       ^
    gyp ERR! stack SyntaxError: invalid syntax
    gyp ERR! stack
    gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:12)
    gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
    gyp ERR! stack     at maybeClose (node:internal/child_process:1063:16)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
    gyp ERR! System Windows_NT 10.0.19042
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\facemunch\\webiny\\project-two\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
    gyp ERR! cwd C:\facemunch\webiny\project-two\node_modules\node-sass
    gyp ERR! node -v v15.5.0
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok
    Build failed with error code: 1
    yarn install v1.22.10
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    info fsevents@2.1.3: The platform "win32" is incompatible with this module.
    info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
    info fsevents@1.2.13: The platform "win32" is incompatible with this module.
    info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
    info fsevents@2.2.1: The platform "win32" is incompatible with this module.
    info "fsevents@2.2.1" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    ----------------------------------------

    Please open an issue including the error output at https://github.com/webiny/webiny-js/issues/new.
    You can also get in touch with us on our Slack Community: https://www.webiny.com/slack

  Writing log to C:\facemunch\webiny\cwp-logs.txt...
  Cleaning up project...
  Project cleaned!
npm ERR! code 1
npm ERR! path C:\facemunch\webiny
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-webiny-project project-two

npm ERR! A complete log of this run can be found in:

## Steps to Reproduce the Problem
1. Re-start laptop
2. Open VS Code at parent folder "C:\facemunch\webiny"
3. In GitBash terminal run "npx create-webiny-project project-two"

## Detailed Description
Re-start laptop then ran create-webiny-project - fails every time.

## Possible Solution
?

**Comment by compositeFlows** [comment]
It works with node v14.15.3 
But npm complains about several high vulnerabilities 
And Jest won’t run on scaffolded books without an extra library
