### ISSUE TITLE
Tailwind CSS Tutorial yarn add error

### ISSUE THREAD

**Issue by adrozdenko** [webiny/webiny-js#1911]
### Version
5.14

### Operating System
Mac OS

### Browser
Chrome

### What steps will reproduce the bug?
Open https://www.webiny.com/docs/how-to-guides/integrations/integrate-tailwindcss/
Copy yarn add -D tailwindcss@npm:@tailwindcss/postcss7-compat^2.1.2 postcss@^7 autoprefixer@^9
Paste it in the terminal which is on Webiny project root directory
Press Enter

### What is the expected behavior?
```
"@tailwindcss/postcss7-compat": "^2.2.7",
"autoprefixer": "^9",
"postcss": "^7"
```

Should be added to package.json file and installed to node modules folder

### What do you see instead?
Errro: 
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: tailwindcss@npm:@tailwindcss/postcss7-compat^2.1.2 isn't supported by any available resolver
    at Xc.getResolverByDescriptor (/Users/drozd/Desktop/aquaty-website-webiny/aquaty-website-webiny/.yarn/releases/yarn-berry.cjs:294:5330)
    at Xc.bindDescriptor (/Users/drozd/Desktop/aquaty-website-webiny/aquaty-website-webiny/.yarn/releases/yarn-berry.cjs:294:4719)
    at p (/Users/drozd/Desktop/aquaty-website-webiny/aquaty-website-webiny/.yarn/releases/yarn-berry.cjs:303:6959)
    at async Promise.all (index 0)
    at async Fe.resolveEverything (/Users/drozd/Desktop/aquaty-website-webiny/aquaty-website-webiny/.yarn/releases/yarn-berry.cjs:303:8166)
    at async /Users/drozd/Desktop/aquaty-website-webiny/aquaty-website-webiny/.yarn/releases/yarn-berry.cjs:306:2135
    at async xe.startTimerPromise (/Users/drozd/Desktop/aquaty-website-webiny/aquaty-website-webiny/.yarn/releases/yarn-berry.cjs:275:3730)
    at async Fe.install (/Users/drozd/Desktop/aquaty-website-webiny/aquaty-website-webiny/.yarn/releases/yarn-berry.cjs:306:2074)
    at async /Users/drozd/Desktop/aquaty-website-webiny/aquaty-website-webiny/.yarn/releases/yarn-berry.cjs:311:122
    at async Function.start (/Users/drozd/Desktop/aquaty-website-webiny/aquaty-website-webiny/.yarn/releases/yarn-berry.cjs:275:2287)
➤ YN0000: └ Completed in 0s 223ms
➤ YN0000: Failed with errors in 0s 226ms

### Possible solution
Update yarn add command

**Comment by tjsb** [comment]
it should be `yarn add -D tailwindcss@npm:@tailwindcss/postcss7-compat@^2.1.2 postcss@^7 autoprefixer@^9`

**Comment by Pavel910** [comment]
Closing this as we now use webpack 5, and the tutorial was updated with new packages and commands.
