### ISSUE TITLE
Unable to build graphql after upgrade to 5.15.0

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#1938]
### Version

5.15.0

### Operating System

Mac

### Browser

Firefox

### What steps will reproduce the bug?

Upgrade to 5.15.0, yarn install, deploy api

### What is the expected behavior?

graphql request should work

### What do you see instead?

The following error appears in cloudwatch logs for the graphql lambda:
```
2021-09-30T18:30:42.516Z	3b37c946-cf7b-4290-9eb9-dc897c444881	INFO	o [Error]: Missing "pb.storageOperationsProvider.menu" plugin.
    at t.createStorageOperations (/var/task/handler.js:15:25162)
    at a._callable (/var/task/handler.js:114:37254)
    at apply (/var/task/handler.js:8:520)
    at /var/task/handler.js:45:204318
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Runtime.handler (/var/task/handler.js:45:204202) {
  code: 'PLUGIN_NOT_FOUND',
  data: { type: 'pb.storageOperationsProvider.menu' }
```
### Additional information

Rolling back to 5.14.0 fixes the problem.

**Comment by snstanton** [comment]
I believe the issue is that the upgrade documentation does not mention the required `yarn webiny upgrade` step that must occur between the `yarn up` and the deploy

**Comment by adrians5j** [comment]
You're right, the `yarn webiny upgrade` step was missing in the upgrade guide. I added it now (https://www.webiny.com/docs/release-notes/5.15.0/upgrade-guide/).

Thanks for letting us know! 🚀 

BTW I assume all is good for you now, so I'll close this issue.
