### ISSUE TITLE
Unable to deploy following the Install tutorial (MacOS)

### ISSUE THREAD

**Issue by icex** [webiny/webiny-js#2036]
### Version

5.17.3

### Operating System

MacOS 12.0.1 (21A559) x86

### Browser

MS Edge

### What steps will reproduce the bug?

```
npx create-webiny-project my-new-project
cd my-new-project
yarn webiny deploy
```

### What is the expected behavior?

I'm trying to install and tryout Webiny but it seems to fail. My AWS is set up with aws cli. 

### What do you see instead?

❯ npx create-webiny-project my-new-project

Initializing a new Webiny project in /Users/bogdan/my-new-project...
  ✔ Prepare project folder
  ✔ Setup yarn
  ✔ Install template package
  ✔ Initialize git
Starting @webiny/cwp-template-aws template ...

In order to setup your new Webiny project, please answer the following questions.

? Please choose the AWS region in which your new project will be deployed: eu-central-1 (EU, Frankfurt)
⏳ Installing dependencies....

➤ YN0000: ┌ Resolution step
➤ YN0061: │ eslint-plugin-standard@npm:5.0.0 is deprecated: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316
➤ YN0013: │ @webiny/ui@npm:5.17.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ @rmwc/textfield@file:./rmwc/textfield#./rmwc/textfield::hash=43ad6e&locator=%40webiny%2Fui%40npm%3A5.17.3 can't be found in the ca
➤ YN0061: │ i18n-locales@npm:0.0.2 is deprecated: Please upgrade to v0.0.3+ as we have fixed missing ISO-639-1 codes
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
➤ YN0061: │ eslint-loader@npm:3.0.2 is deprecated: This loader has been deprecated. Please use eslint-webpack-plugin
➤ YN0061: │ html-webpack-plugin@npm:4.0.0-beta.5 is deprecated: please switch to a stable version
➤ YN0061: │ react-images@npm:0.5.19 is deprecated: This beta version is no longer supported. Please update to 1.1.0-beta.4
➤ YN0061: │ deep-assign@npm:3.0.0 is deprecated: Check out `lodash.merge` or `merge-options` instead.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ @babel/polyfill@npm:7.12.1 is deprecated: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
➤ YN0032: │ nan@npm:2.15.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ svgo@npm:1.3.2 is deprecated: This SVGO version is no longer supported. Upgrade to v2.x.x.
➤ YN0061: │ sane@npm:4.1.0 is deprecated: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [2ed40] doesn't provide apollo-utilities (pab545), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [443cb] doesn't provide apollo-utilities (p34305), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [4e179] doesn't provide apollo-utilities (p7b9fa), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [5b07d] doesn't provide apollo-utilities (pe4b27), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [6ddac] doesn't provide apollo-utilities (p4bc45), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [8109d] doesn't provide apollo-utilities (pefce3), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [820e3] doesn't provide apollo-utilities (p2f0a7), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [c50e3] doesn't provide apollo-utilities (pe7650), requested by @apollo/react-common
➤ YN0002: │ @aws-sdk/middleware-retry@npm:3.6.1 doesn't provide react-native (p55852), requested by react-native-get-random-values
➤ YN0002: │ @webiny/api-headless-cms@npm:5.17.3 doesn't provide graphql (p506e9), requested by @graphql-tools/schema
➤ YN0002: │ @webiny/api-prerendering-service@npm:5.17.3 doesn't provide puppeteer-core (pdcea8), requested by chrome-aws-lambda
➤ YN0002: │ @webiny/app-admin-cognito@npm:5.17.3 doesn't provide @emotion/core (p02ac8), requested by @emotion/styled
➤ YN0002: │ @webiny/app-admin-cognito@npm:5.17.3 doesn't provide @types/react (p234fb), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-admin-cognito@npm:5.17.3 doesn't provide graphql (p4da96), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-admin-cognito@npm:5.17.3 doesn't provide graphql (p516c8), requested by apollo-client
➤ YN0002: │ @webiny/app-admin-users-cognito@npm:5.17.3 doesn't provide @emotion/core (p34c57), requested by @emotion/styled
➤ YN0002: │ @webiny/app-admin-users-cognito@npm:5.17.3 doesn't provide @types/react (p59cf5), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-admin-users-cognito@npm:5.17.3 doesn't provide apollo-client (p438e5), requested by @apollo/react-hooks
➤ YN0060: │ @webiny/app-page-builder@npm:5.17.3 provides react-dnd (pc4416) with version 9.5.1, which doesn't satisfy what react-sortable-tree and some of its descendants request
➤ YN0002: │ @webiny/app-security-access-management@npm:5.17.3 doesn't provide @emotion/core (p518b8), requested by @emotion/styled
➤ YN0002: │ @webiny/app-security-access-management@npm:5.17.3 doesn't provide @types/react (ped86f), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-security-access-management@npm:5.17.3 doesn't provide apollo-client (pc0fdb), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-security-access-management@npm:5.17.3 doesn't provide graphql (pf1970), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-security-access-management@npm:5.17.3 doesn't provide graphql (p0b922), requested by graphql-tag
➤ YN0002: │ @webiny/app-tenancy@npm:5.17.3 doesn't provide @emotion/core (p5f449), requested by @emotion/styled
➤ YN0002: │ @webiny/app-tenancy@npm:5.17.3 doesn't provide apollo-client (pa6505), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-tenancy@npm:5.17.3 doesn't provide graphql (p0f5e8), requested by graphql-tag
➤ YN0002: │ @webiny/app-tenancy@npm:5.17.3 doesn't provide graphql (pc0669), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app@npm:5.17.3 doesn't provide @emotion/core (pc3813), requested by @emotion/styled
➤ YN0002: │ admin@workspace:apps/admin/code doesn't provide graphql (p42fcd), requested by apollo-link
➤ YN0002: │ admin@workspace:apps/admin/code doesn't provide graphql (pd7e59), requested by apollo-client
➤ YN0002: │ admin@workspace:apps/admin/code doesn't provide graphql (p18a18), requested by @apollo/react-components
➤ YN0002: │ admin@workspace:apps/admin/code doesn't provide graphql (p2eb75), requested by apollo-link-batch-http
➤ YN0002: │ apollo-link-batch@npm:1.1.15 doesn't provide graphql (pc3653), requested by apollo-link
➤ YN0002: │ apollo-link-context@npm:1.0.20 doesn't provide graphql (pa199c), requested by apollo-link
➤ YN0002: │ apollo-link-error@npm:1.1.13 doesn't provide graphql (p4f6d1), requested by apollo-link
➤ YN0002: │ apollo-link-error@npm:1.1.13 doesn't provide graphql (pbcdcb), requested by apollo-link-http-common
➤ YN0002: │ posthtml-plugin-link-preload@npm:1.0.0 doesn't provide posthtml (p07a8b), requested by posthtml-match-helper
➤ YN0002: │ rc-trigger@npm:2.6.5 doesn't provide react (p8a8f0), requested by rc-animate
➤ YN0002: │ rc-trigger@npm:2.6.5 doesn't provide react-dom (p1433f), requested by rc-animate
➤ YN0002: │ react-dev-utils@npm:10.2.1 doesn't provide typescript (p62ad2), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-dev-utils@npm:10.2.1 doesn't provide webpack (p2e56c), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-scrolllock@npm:2.0.7 doesn't provide react (p6ac0d), requested by react-prop-toggle
➤ YN0002: │ react-scrolllock@npm:2.0.7 doesn't provide react-dom (pc58d4), requested by react-prop-toggle
➤ YN0002: │ theme@workspace:apps/theme doesn't provide @types/react (p774d2), requested by @apollo/react-components
➤ YN0002: │ theme@workspace:apps/theme doesn't provide apollo-cache (p1ef5e), requested by @apollo/react-components
➤ YN0002: │ theme@workspace:apps/theme doesn't provide apollo-client (p32b13), requested by @apollo/react-components
➤ YN0002: │ theme@workspace:apps/theme doesn't provide apollo-link (p210ed), requested by @apollo/react-components
➤ YN0002: │ theme@workspace:apps/theme doesn't provide apollo-utilities (p4b8bc), requested by @apollo/react-components
➤ YN0002: │ theme@workspace:apps/theme doesn't provide prop-types (p2d2f0), requested by react-hamburger-menu
➤ YN0002: │ theme@workspace:apps/theme doesn't provide react-dom (p98606), requested by @apollo/react-components
➤ YN0002: │ website@workspace:apps/website/code doesn't provide apollo-cache (p86d46), requested by @apollo/react-components
➤ YN0002: │ website@workspace:apps/website/code doesn't provide apollo-utilities (p10aef), requested by @apollo/react-components
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 35s 535ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ zerop@npm:1.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zip-local@npm:0.3.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zip-stream@npm:4.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0019: │ typescript-npm-3.7.7-f42300f02a-b34e855336.zip appears to be unused - removing
➤ YN0019: │ typescript-patch-9600e89e56-61283b54e3.zip appears to be unused - removing
➤ YN0000: └ Completed in 3s 10ms
➤ YN0000: ┌ Link step
➤ YN0007: │ my-new-project@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.19.1 must be built because it never has been before or the last one failed
➤ YN0008: │ @pulumi/aws@npm:4.28.0 must be rebuilt because its dependency tree changed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-common-types@npm:0.2.36 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-svg-core@npm:1.2.36 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-brands-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-regular-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-solid-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 16s 366ms
➤ YN0000: Done with warnings in 55s 205ms

🎉 Your new Webiny project my-new-project is ready!

Finish the setup by running the following command: cd my-new-project && yarn webiny deploy

To see all of the available CLI commands, run yarn webiny --help in your my-new-project directory.

Want to dive deeper into Webiny? Check out https://webiny.com/docs/!
Like the project? Star us on https://github.com/webiny/webiny-js!

Need help? Join our Slack community! https://www.webiny.com/slack

🚀 Happy coding!

❯ cd my-new-project && yarn webiny deploy
It looks like this is your first time using @webiny/pulumi-sdk.
✔ Pulumi downloaded, continuing...
[resource plugin aws-4.28.0] installing
Downloading plugin: 95.71 MiB / 95.71 MiB [=========================] 100.00% 1s

webiny info: This is your first time deploying the project (dev environment). Note that the initial deployment can take up to 15 minutes, so please be patient.

webiny info: Deploying api project application...
webiny info: Running 'build' in 15 packages...
api-file-manager-manage: webiny log: Start bundling
api-page-builder-import-pages-create: webiny log: Start bundling
api-file-manager-download: webiny log: Start bundling
api-dynamo-to-elastic: webiny log: Start bundling
api-file-manager-transform: webiny log: Start bundling
api-page-builder-export-pages-process: webiny log: Start bundling
api-graphql: webiny log: Start bundling
api-page-builder-update-settings: webiny log: Start bundling
api-headless-cms: webiny log: Start bundling
api-page-builder-export-pages-combine: webiny log: Start bundling
api-prerendering-service-flush: webiny log: Start bundling
api-page-builder-import-pages-process: webiny log: Start bundling
api-prerendering-service-queue-add: webiny log: Start bundling
api-prerendering-service-render: webiny log: Start bundling
api-prerendering-service-queue-process: webiny log: Start bundling
api-page-builder-import-pages-create: ℹ Compiling Create
api-file-manager-transform: ℹ Compiling Transform
api-dynamo-to-elastic: ℹ Compiling DynamoToElastic
api-prerendering-service-flush: ℹ Compiling Flush
api-page-builder-export-pages-process: ℹ Compiling Process
api-page-builder-import-pages-process: ℹ Compiling Process
api-headless-cms: ℹ Compiling HeadlessCMS
api-file-manager-manage: ℹ Compiling Manage
api-graphql: ℹ Compiling Graphql
api-page-builder-update-settings: ℹ Compiling UpdateSettings
api-file-manager-download: ℹ Compiling Download
api-page-builder-export-pages-combine: ℹ Compiling Combine
api-prerendering-service-queue-add: ℹ Compiling Add
api-prerendering-service-render: ℹ Compiling Render
api-prerendering-service-queue-process: ℹ Compiling Process
api-file-manager-manage: ✔ Manage: Compiled successfully in 1.93s
api-file-manager-manage: webiny log: Finished bundling
api-file-manager-transform: ✔ Transform: Compiled successfully in 2.00s
api-file-manager-transform: webiny log: Finished bundling
api-file-manager-download: ✔ Download: Compiled successfully in 2.06s
api-file-manager-download: webiny log: Finished bundling
api-prerendering-service-queue-add: ✔ Add: Compiled successfully in 3.68s
api-prerendering-service-queue-add: webiny log: Finished bundling
api-prerendering-service-flush: ✔ Flush: Compiled successfully in 3.72s
api-prerendering-service-flush: webiny log: Finished bundling
api-prerendering-service-queue-process: ✔ Process: Compiled successfully in 3.92s
api-prerendering-service-queue-process: webiny log: Finished bundling
api-prerendering-service-render: ✔ Render: Compiled successfully in 5.69s
api-prerendering-service-render: webiny log: Finished bundling
api-dynamo-to-elastic: ✔ DynamoToElastic: Compiled successfully in 5.79s
api-dynamo-to-elastic: webiny log: Finished bundling
api-page-builder-update-settings: ✔ UpdateSettings: Compiled successfully in 6.07s
api-page-builder-update-settings: webiny log: Finished bundling
api-headless-cms: ✔ HeadlessCMS: Compiled successfully in 15.84s
api-headless-cms: webiny log: Finished bundling
api-page-builder-import-pages-create: ✔ Create: Compiled successfully in 16.97s
api-page-builder-import-pages-create: webiny log: Finished bundling
api-page-builder-export-pages-combine: ✔ Combine: Compiled successfully in 17.03s
api-page-builder-export-pages-combine: webiny log: Finished bundling
api-page-builder-import-pages-process: ✔ Process: Compiled successfully in 17.44s
api-page-builder-import-pages-process: webiny log: Finished bundling
api-page-builder-export-pages-process: ✔ Process: Compiled successfully in 17.49s
api-page-builder-export-pages-process: webiny log: Finished bundling
api-graphql: ✔ Graphql: Compiled successfully in 20.39s
api-graphql: webiny log: Finished bundling
webiny error: Command failed with exit code 255: /Users/bogdan/my-new-project/.webiny/pulumi-cli/darwin/pulumi/pulumi stack select dev --create --secrets-provider passphrase --non-interactive
error: failed to load checkpoint: blob (key ".pulumi/stacks/dev.json") (code=NotFound): stat /Users/bogdan/my-new-project/.pulumi/api/.pulumi/stacks/dev.json: no such file or directory
webiny debug:  Error: Command failed with exit code 255: /Users/bogdan/my-new-project/.webiny/pulumi-cli/darwin/pulumi/pulumi stack select dev --create --secrets-provider passphrase --non-interactive
error: failed to load checkpoint: blob (key ".pulumi/stacks/dev.json") (code=NotFound): stat /Users/bogdan/my-new-project/.pulumi/api/.pulumi/stacks/dev.json: no such file or directory
    at makeError (/Users/bogdan/my-new-project/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/bogdan/my-new-project/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at module.exports (/Users/bogdan/my-new-project/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy.js:69:5)
    at Object.handler (/Users/bogdan/my-new-project/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/index.js:47:21) {
  shortMessage: 'Command failed with exit code 255: /Users/bogdan/my-new-project/.webiny/pulumi-cli/darwin/pulumi/pulumi stack select dev --create --secrets-provider passphrase --non-interactive',
  command: '/Users/bogdan/my-new-project/.webiny/pulumi-cli/darwin/pulumi/pulumi stack select dev --create --secrets-provider passphrase --non-interactive',
  exitCode: 255,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'error: failed to load checkpoint: blob (key ".pulumi/stacks/dev.json") (code=NotFound): stat /Users/bogdan/my-new-project/.pulumi/api/.pulumi/stacks/dev.json: no such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

webiny error: Command failed with exit code 1: yarn webiny deploy api --env dev --debug false --build true --preview false

### Additional information
Seems to be a Mac OS issue, I managed to get it working using Ubuntu 21.04.

❯ node -v
v14.17.3

❯ npm -v
7.20.0

**Comment by icex** [comment]
I think I managed to make it work.. `rm -rf ~/.npm`
