### ISSUE TITLE
yarn webiny deploy typescript errors: error TS2688

### ISSUE THREAD

**Issue by jcalfee** [webiny/webiny-js#2194]
### Version

5.21.0

### Operating System

Debian GNU/Linux 11 (bullseye)

### Browser

n/a

### What steps will reproduce the bug?

Follow the guide exactly, using Node 12, DynamoDB only, then:
> yarn webiny deploy

### What do you see instead?

```
$ yarn webiny deploy
webiny info: Deploying api project application...
webiny info: Running "hook-before-build" hook...
webiny success: Hook "hook-before-build" completed.
webiny info: Building 14 packages...

webiny success: api-file-manager-manage (18.936s)
webiny success: api-file-manager-download (19.028s)
webiny success: api-file-manager-transform (19.401s)
webiny success: api-prerendering-service-flush (21.313s)
webiny success: api-prerendering-service-queue-add (22.647s)
webiny success: api-prerendering-service-queue-process (22.856s)
webiny success: api-prerendering-service-render (24.864s)
webiny success: api-page-builder-update-settings (25.236s)
webiny success: api-page-builder-import-pages-create (40.749s)
webiny success: api-page-builder-export-pages-combine (41.373s)
webiny success: api-page-builder-export-pages-process (42.581s)
webiny success: api-page-builder-import-pages-process (42.684s)
webiny success: api-headless-cms (43.573s)
webiny success: api-graphql (46.179s)

webiny success: Successfully built 14 packages in 47.183s.
webiny info: Running "hook-after-build" hook...
webiny success: Hook "hook-after-build" completed.

webiny info: Running "hook-before-deploy" hook...
webiny info: Using profile default in us-east-1 region.
webiny success: Hook "hook-before-deploy" completed.

webiny info: Deploying...

Updating (dev):

    pulumi:pulumi:Stack api-dev running 
    pulumi:pulumi:Stack api-dev running error: Running program '/home/james/dev/webiny/api/pulumi' failed with an unhandled exception:
    pulumi:pulumi:Stack api-dev **failed** 1 error
 
Diagnostics:
  pulumi:pulumi:Stack (api-dev):
    error: Running program '/home/james/dev/webiny/api/pulumi' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    error TS2688: Cannot find type definition file for 'base64-arraybuffer'.
    error TS2688: Cannot find type definition file for 'bent'.
    error TS2688: Cannot find type definition file for 'body-parser'.
    error TS2688: Cannot find type definition file for 'caseless'.
    error TS2688: Cannot find type definition file for 'connect'.
    error TS2688: Cannot find type definition file for 'diff'.
    error TS2688: Cannot find type definition file for 'dompurify'.
    error TS2688: Cannot find type definition file for 'events'.
    error TS2688: Cannot find type definition file for 'express'.
    error TS2688: Cannot find type definition file for 'express-serve-static-core'.
    error TS2688: Cannot find type definition file for 'fs-extra'.
    error TS2688: Cannot find type definition file for 'linkify-it'.
    error TS2688: Cannot find type definition file for 'lodash'.
    error TS2688: Cannot find type definition file for 'lodash.debounce'.
    error TS2688: Cannot find type definition file for 'lodash.throttle'.
    error TS2688: Cannot find type definition file for 'markdown-it'.
    error TS2688: Cannot find type definition file for 'markdown-it-anchor'.
    error TS2688: Cannot find type definition file for 'mdurl'.
    error TS2688: Cannot find type definition file for 'mime-types'.
    error TS2688: Cannot find type definition file for 'multer'.
    error TS2688: Cannot find type definition file for 'p-queue'.
    error TS2688: Cannot find type definition file for 'qs'.
    error TS2688: Cannot find type definition file for 'range-parser'.
    error TS2688: Cannot find type definition file for 'react-virtualized'.
    error TS2688: Cannot find type definition file for 'request'.
    error TS2688: Cannot find type definition file for 'rimraf'.
    error TS2688: Cannot find type definition file for 'route-parser'.
    error TS2688: Cannot find type definition file for 'safer-buffer'.
    error TS2688: Cannot find type definition file for 'scheduler'.
    error TS2688: Cannot find type definition file for 'semver'.
    error TS2688: Cannot find type definition file for 'serve-static'.
    error TS2688: Cannot find type definition file for 'showdown'.
    error TS2688: Cannot find type definition file for 'tar-fs'.
    error TS2688: Cannot find type definition file for 'tar-stream'.
    error TS2688: Cannot find type definition file for 'tough-cookie'.
    error TS2688: Cannot find type definition file for 'trusted-types'.
    error TS2688: Cannot find type definition file for 'uuid'.
    error TS2688: Cannot find type definition file for 'which'.
    error TS2688: Cannot find type definition file for 'ws'.
    
        at createTSError (/home/james/dev/webiny/node_modules/ts-node/src/index.ts:261:12)
        at getOutput (/home/james/dev/webiny/node_modules/ts-node/src/index.ts:367:40)
        at Object.compile (/home/james/dev/webiny/node_modules/ts-node/src/index.ts:558:11)
        at Module.m._compile (/home/james/dev/webiny/node_modules/ts-node/src/index.ts:439:43)
        at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
        at Object.require.extensions.<computed> [as .ts] (/home/james/dev/webiny/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:863:32)
        at Function.Module._load (internal/modules/cjs/loader.js:708:14)
        at Module.require (internal/modules/cjs/loader.js:887:19)
        at require (internal/modules/cjs/helpers.js:74:18)
 
Resources:
    1 unchanged

Duration: 17s

webiny error: Command failed with exit code 255: /home/james/dev/webiny/.webiny/pulumi-cli/linux/pulumi/pulumi up --yes --skip-preview --secrets-provider passphrase --non-interactive
webiny debug:  Error: Command failed with exit code 255: /home/james/dev/webiny/.webiny/pulumi-cli/linux/pulumi/pulumi up --yes --skip-preview --secrets-provider passphrase --non-interactive
    at makeError (/home/james/dev/webiny/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/james/dev/webiny/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at module.exports (/home/james/dev/webiny/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy.js:118:9)
    at Object.handler (/home/james/dev/webiny/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/index.js:57:21) {
  shortMessage: 'Command failed with exit code 255: /home/james/dev/webiny/.webiny/pulumi-cli/linux/pulumi/pulumi up --yes --skip-preview --secrets-provider passphrase --non-interactive',
  command: '/home/james/dev/webiny/.webiny/pulumi-cli/linux/pulumi/pulumi up --yes --skip-preview --secrets-provider passphrase --non-interactive',
  exitCode: 255,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

webiny error: Command failed with exit code 1: yarn webiny deploy api --env dev --debug false --build true --preview false
```

### Additional information

```
$ npx create-webiny-project webiny
npx: installed 177 in 25.141s
Initializing a new Webiny project in /home/james/dev/webiny...
  ✔ Prepare project folder
  ✔ Setup yarn
  ✔ Install template package
  ✔ Initialize git
Starting @webiny/cwp-template-aws template ...

In order to setup your new Webiny project, please answer the following questions.

? Please choose the AWS region in which your new project will be deployed: us-east-1 (US East, N. Virginia)
? Please choose the database you wish to use with your Webiny project: DynamoDB (for small and medium sized projects)
⏳ Installing dependencies....

➤ YN0000: ┌ Resolution step
➤ YN0061: │ eslint-plugin-standard@npm:5.0.0 is deprecated: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316
➤ YN0061: │ eslint-loader@npm:3.0.2 is deprecated: This loader has been deprecated. Please use eslint-webpack-plugin
➤ YN0061: │ html-webpack-plugin@npm:4.0.0-beta.5 is deprecated: please switch to a stable version
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
➤ YN0061: │ i18n-locales@npm:0.0.2 is deprecated: Please upgrade to v0.0.3+ as we have fixed missing ISO-639-1 codes
➤ YN0013: │ @webiny/ui@npm:5.21.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ @rmwc/textfield@file:./rmwc/textfield#./rmwc/textfield::hash=43ad6e&locator=%40webiny%2Fui%40npm%3A5.21.0 can't be found in
➤ YN0061: │ react-images@npm:0.5.19 is deprecated: This beta version is no longer supported. Please update to 1.1.0-beta.4
➤ YN0061: │ deep-assign@npm:3.0.0 is deprecated: Check out `lodash.merge` or `merge-options` instead.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ svgo@npm:1.3.2 is deprecated: This SVGO version is no longer supported. Upgrade to v2.x.x.
➤ YN0032: │ nan@npm:2.15.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ sane@npm:4.1.0 is deprecated: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
➤ YN0061: │ @babel/polyfill@npm:7.12.1 is deprecated: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [1ee5a] doesn't provide apollo-utilities (p90fea), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [289ed] doesn't provide apollo-utilities (pf2e4d), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [d8cba] doesn't provide apollo-utilities (p83d74), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [e1d2b] doesn't provide apollo-utilities (p21b89), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [e1ea5] doesn't provide apollo-utilities (pcee9e), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [e4408] doesn't provide apollo-utilities (p0e401), requested by @apollo/react-common
➤ YN0002: │ @apollo/react-hooks@npm:3.1.5 [e75ea] doesn't provide apollo-utilities (p80680), requested by @apollo/react-common
➤ YN0002: │ @aws-sdk/middleware-retry@npm:3.6.1 doesn't provide react-native (p38415), requested by react-native-get-random-values
➤ YN0002: │ @webiny/api-headless-cms@npm:5.21.0 doesn't provide graphql (p3415f), requested by @graphql-tools/schema
➤ YN0002: │ @webiny/api-prerendering-service@npm:5.21.0 doesn't provide puppeteer-core (pb4058), requested by chrome-aws-lambda
➤ YN0002: │ @webiny/app-admin-cognito@npm:5.21.0 doesn't provide @emotion/core (pb610b), requested by @emotion/styled
➤ YN0002: │ @webiny/app-admin-cognito@npm:5.21.0 doesn't provide @types/react (p4ee4b), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-admin-cognito@npm:5.21.0 doesn't provide graphql (p38b5e), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-admin-cognito@npm:5.21.0 doesn't provide graphql (pf6b9b), requested by apollo-client
➤ YN0002: │ @webiny/app-admin-rmwc@npm:5.21.0 doesn't provide @emotion/core (pb2012), requested by @emotion/styled
➤ YN0002: │ @webiny/app-admin-users-cognito@npm:5.21.0 doesn't provide @emotion/core (p9012f), requested by @emotion/styled
➤ YN0002: │ @webiny/app-admin-users-cognito@npm:5.21.0 doesn't provide @types/react (p1a5a3), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-admin-users-cognito@npm:5.21.0 doesn't provide apollo-client (p9bfb9), requested by @apollo/react-hooks
➤ YN0060: │ @webiny/app-page-builder@npm:5.21.0 provides react-dnd (pf33e8) with version 9.5.1, which doesn't satisfy what react-sortable-tree and some of its descendants request
➤ YN0002: │ @webiny/app-security-access-management@npm:5.21.0 doesn't provide @emotion/core (p3ba6c), requested by @emotion/styled
➤ YN0002: │ @webiny/app-security-access-management@npm:5.21.0 doesn't provide @types/react (p9d27e), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-security-access-management@npm:5.21.0 doesn't provide apollo-client (pabf95), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-security-access-management@npm:5.21.0 doesn't provide graphql (p19ffe), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-security-access-management@npm:5.21.0 doesn't provide graphql (p97c6a), requested by graphql-tag
➤ YN0002: │ @webiny/app-serverless-cms@npm:5.21.0 doesn't provide graphql (p5f05f), requested by apollo-link
➤ YN0002: │ @webiny/app-serverless-cms@npm:5.21.0 doesn't provide graphql (p538e1), requested by apollo-client
➤ YN0002: │ @webiny/app-serverless-cms@npm:5.21.0 doesn't provide graphql (p9281b), requested by apollo-link-batch-http
➤ YN0002: │ @webiny/app-tenancy@npm:5.21.0 doesn't provide @emotion/core (pa4eab), requested by @emotion/styled
➤ YN0002: │ @webiny/app-tenancy@npm:5.21.0 doesn't provide apollo-client (p64bfc), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app-tenancy@npm:5.21.0 doesn't provide graphql (p32128), requested by graphql-tag
➤ YN0002: │ @webiny/app-tenancy@npm:5.21.0 doesn't provide graphql (p39485), requested by @apollo/react-hooks
➤ YN0002: │ @webiny/app@npm:5.21.0 doesn't provide @emotion/core (pb411e), requested by @emotion/styled
➤ YN0002: │ @webiny/project-utils@npm:5.21.0 doesn't provide ts-node (pbbcbb), requested by ttypescript
➤ YN0002: │ @webiny/project-utils@npm:5.21.0 doesn't provide typescript (p779ba), requested by ttypescript
➤ YN0002: │ apollo-link-batch@npm:1.1.15 doesn't provide graphql (pc3653), requested by apollo-link
➤ YN0002: │ apollo-link-context@npm:1.0.20 doesn't provide graphql (pa199c), requested by apollo-link
➤ YN0002: │ apollo-link-error@npm:1.1.13 doesn't provide graphql (p4f6d1), requested by apollo-link
➤ YN0002: │ apollo-link-error@npm:1.1.13 doesn't provide graphql (pbcdcb), requested by apollo-link-http-common
➤ YN0002: │ posthtml-plugin-link-preload@npm:1.0.0 doesn't provide posthtml (p07a8b), requested by posthtml-match-helper
➤ YN0002: │ rc-trigger@npm:2.6.5 doesn't provide react (p8a8f0), requested by rc-animate
➤ YN0002: │ rc-trigger@npm:2.6.5 doesn't provide react-dom (p1433f), requested by rc-animate
➤ YN0002: │ react-dev-utils@npm:10.2.1 doesn't provide typescript (p62ad2), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-dev-utils@npm:10.2.1 doesn't provide webpack (p2e56c), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-scrolllock@npm:2.0.7 doesn't provide react (p6ac0d), requested by react-prop-toggle
➤ YN0002: │ react-scrolllock@npm:2.0.7 doesn't provide react-dom (pc58d4), requested by react-prop-toggle
➤ YN0002: │ theme@workspace:apps/theme doesn't provide @types/react (pb63d5), requested by @apollo/react-hooks
➤ YN0002: │ theme@workspace:apps/theme doesn't provide @types/react (p774d2), requested by @apollo/react-components
➤ YN0002: │ theme@workspace:apps/theme doesn't provide apollo-cache (p1ef5e), requested by @apollo/react-components
➤ YN0002: │ theme@workspace:apps/theme doesn't provide apollo-client (pa84c3), requested by @apollo/react-hooks
➤ YN0002: │ theme@workspace:apps/theme doesn't provide apollo-client (p32b13), requested by @apollo/react-components
➤ YN0002: │ theme@workspace:apps/theme doesn't provide apollo-link (p210ed), requested by @apollo/react-components
➤ YN0002: │ theme@workspace:apps/theme doesn't provide apollo-utilities (p4b8bc), requested by @apollo/react-components
➤ YN0002: │ theme@workspace:apps/theme doesn't provide prop-types (p2d2f0), requested by react-hamburger-menu
➤ YN0002: │ theme@workspace:apps/theme doesn't provide react-dom (pa4177), requested by @apollo/react-hooks
➤ YN0002: │ theme@workspace:apps/theme doesn't provide react-dom (p98606), requested by @apollo/react-components
➤ YN0002: │ website@workspace:apps/website/code doesn't provide apollo-cache (p86d46), requested by @apollo/react-components
➤ YN0002: │ website@workspace:apps/website/code doesn't provide apollo-utilities (p10aef), requested by @apollo/react-components
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 49s 768ms
➤ YN0000: ┌ Fetch step
➤ YN0019: │ @pulumi-aws-npm-4.34.0-45e4fc861f-3074ffca01.zip appears to be unused - removing
➤ YN0019: │ @pulumi-pulumi-npm-3.17.1-c8ce910b10-bff6369897.zip appears to be unused - removing
➤ YN0019: │ @pulumi-pulumi-npm-3.22.1-3d954e03a4-402f6d7a7f.zip appears to be unused - removing
➤ YN0019: │ typescript-npm-3.7.7-f42300f02a-b34e855336.zip appears to be unused - removing
➤ YN0019: │ typescript-patch-635d6c0f88-61283b54e3.zip appears to be unused - removing
➤ YN0000: └ Completed in 8s 280ms
➤ YN0000: ┌ Link step
➤ YN0076: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0007: │ webiny@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.20.3 must be built because it never has been before or the last one failed
➤ YN0007: │ @pulumi/aws@npm:4.28.0 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-common-types@npm:0.2.36 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-svg-core@npm:1.2.36 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-brands-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-regular-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-solid-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1m 10s
➤ YN0000: Done with warnings in 2m 9s

🎉 Your new Webiny project webiny is ready!

Finish the setup by running the following command: cd webiny && yarn webiny deploy

To see all of the available CLI commands, run yarn webiny --help in your webiny directory.

Want to dive deeper into Webiny? Check out https://webiny.com/docs/!
Like the project? Star us on https://github.com/webiny/webiny-js!

Need help? Join our Slack community! https://www.webiny.com/slack

🚀 Happy coding!
```

**Comment by jcalfee** [comment]
I removed node_modules switched from node v12 to v14 and deployed successfully.
