### ISSUE TITLE
apps/admin deploy failed to compile on windows

### ISSUE THREAD

**Issue by openstepmedia** [webiny/webiny-js#2220]
### Version

5.22.0

### Operating System

Windows 10 Pro

### Browser

N/A

### What steps will reproduce the bug?

yarn webiny deploy apps/admin --env dev --debug --preview

### What do you see instead?

```
>yarn webiny deploy apps/admin --env dev --debug --preview

webiny success: Successfully loaded environment variables from c:\dev\trxtutorial\.env.
webiny debug: No environment file found on c:\dev\trxtutorial\.env.dev.
webiny debug: No environment file found on c:\dev\trxtutorial\apps\admin\.env.dev.
webiny debug: No environment file found on c:\dev\trxtutorial\apps\admin\.env.
webiny info: Running "hook-before-build" hook...
webiny success: Hook "hook-before-build" completed.
webiny info: Building admin package...

i Compiling Code
√ Code: Compiled with some errors in 2.13m
Module parse failed: Unexpected token (21:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * Feel free to use this component as your starting point for your own form layouts. Add or remove things as you like!
|  */
> const DefaultFormLayout: FormLayoutComponent = ({
|     getFields,
|     getDefaultValues,
Failed to compile.

Module parse failed: Unexpected token (21:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * Feel free to use this component as your starting point for your own form layouts. Add or remove things as you like!
|  */
> const DefaultFormLayout: FormLayoutComponent = ({
|     getFields,
|     getDefaultValues,

webiny error: An error occurred while building admin package.

webiny error: Failed to build all packages (1 error occurred).
webiny debug:  Error: Failed to build all packages (1 error occurred).
    at module.exports (c:\dev\trxtutorial\node_modules\@webiny\cli-plugin-deploy-pulumi\commands\deploy\buildPackages.js:166:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at module.exports (c:\dev\trxtutorial\node_modules\@webiny\cli-plugin-deploy-pulumi\commands\deploy.js:46:9)
    at Object.handler (c:\dev\trxtutorial\node_modules\@webiny\cli-plugin-deploy-pulumi\commands\index.js:57:21)
```

### Additional information

I was able to successfully launch the api application with:
```
yarn webiny deploy api --env dev --debug
```

**Comment by Pavel910** [comment]
@openstepmedia what terminal are you using?

I'm a Windows user myself, and things work fine on my end. Is it plain CMD by any chance? If so, you'll need to use a proper terminal. Use `Windows Terminal` as a host for any terminal, even CMD works fine when used in conjunction with Windows Terminal.

**Comment by Pavel910** [comment]
Just tied this in plan CMD, it builds fine. Please provide a bit more information about your terminal so I can try to reproduce this. Thanks!

![image](https://user-images.githubusercontent.com/3920893/151674454-e989d5d0-3035-4eb5-b94e-3c9f87da9f26.png)

**Comment by openstepmedia** [comment]
@Pavel910 - thanks for that. I was using a CMD window. I will retry in terminal. thanks

**Comment by Pavel910** [comment]
Give it a go and let me know if you can't get rid of this error. I'll be glad to try your setup to see what's wrong (if anything).
I'm using Git Bash in Windows Terminal. In general, Windows Terminal as a host is a good way to go, it handles many inconsistencies between the terminals.
