### ISSUE TITLE
Yarn Webiny Deploy not working with Node 12

### ISSUE THREAD

**Issue by hkbertoson** [webiny/webiny-js#2418]
### Version

yarn run v1.22.18

### Operating System

Mac OS

### Browser

Chrome

### What steps will reproduce the bug?

By running `yarn webiny deploy` I get an error that states:

```
   const config = params.config ?? {};
                                  ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/hkbertoson/Dev/testing/node_modules/@webiny/pulumi-sdk/index.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
(node:69885) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:69885) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I switched to Node 14 and it worked just fine.

**Comment by Pavel910** [comment]
Thanks @hkbertoson. This is because we started using newer node features recently, and it's been some time since we switched to node v14, so we forgot to test with node 12. Since AWS Lambda now also supports node v16, we'll probably be completely moving away from v12.

Is this a huge issue for you? Will you be able to use node 14?

**Comment by hkbertoson** [comment]
Yes. I can use Node 14. Thank you for clarifying.
