### ISSUE TITLE
Error Installing Webiny

### ISSUE THREAD

**Issue by EOEboh** [webiny/webiny-js#2589]
### Version

$ yarn webiny --version yarn run v1.22.19 error Couldn't find a package.json file in "C:\\Users\\USER\\Desktop" info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Operating System

Windows

### Browser

Chrome

### What are the steps to reproduce this bug?

When I run the `npx create-webiny-project my-new-project` command, it begins the steps of creating the folder structure, then suddenly outputs the error below:

### What is the expected behavior?

To see a generated webiny folder structure, so I can proceed to deploy it.

### What do you see instead?

```
Command failed with exit code 1: yarn add @webiny/cwp-template-aws@latest
Γ₧ñ YN0000: Γöî Resolution step
Γ₧ñ YN0061: Γöé flatten@npm:1.0.3 is deprecated: flatten is deprecated in favor of utility frameworks such as lodash.
Γ₧ñ YN0001: Γöé RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\USER\Desktop\my-new-project\.yarn\releases\yarn-3.2.2.cjs:195:14361)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.o.emit (C:\Users\USER\Desktop\my-new-project\.yarn\releases\yarn-3.2.2.cjs:190:90453)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Γ₧ñ YN0000: Γöö Completed in 1m 42s
Γ₧ñ YN0000: Failed with errors in 1m 42s
Γ₧ñ YN0061: querystring@npm:0.2.0 is deprecated: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
Γ₧ñ YN0061: read-package-tree@npm:5.3.1 is deprecated: The functionality that this package provided is now in @npmcli/arborist
```

### Additional information

I have done all the possible troubleshooting.

I have already set up aws credentials.

I have the latest versions of Yarn and Node installed already.

**Comment by Pavel910** [comment]
@EOEboh `ECONNRESET` usually indicates network issues. Have you, by any chance, tried to create a project since then?
