### ISSUE TITLE
Error deploy in macOS - Failed to build all packages

### ISSUE THREAD

**Issue by chrysos** [webiny/webiny-js#3022]
### Version

5.34.3

### Operating System

macOS 12.6.3

### Browser

Chrome 109.0.5414.119

### What are the steps to reproduce this bug?

After I created the project, I ran the command:
`yarn webiny deploy`

And it always gives the same error in the admin step:
```
webiny error: admin
webiny error: admin
(node:38736) Warning: Label 'JIT TOTAL' already exists for console.time()
(Use `node --trace-warnings ...` to show where the warning was created)


webiny error: Failed to build all packages (1 error occurred).
webiny debug:  Error: Failed to build all packages (1 error occurred).
    at module.exports (/Users/dev/Code/webiny/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy/buildPackages.js:167:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at command (/Users/dev/Code/webiny/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy.js:20:17)
    at Object.handler (/Users/dev/Code/webiny/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/index.js:61:21)
```

**Comment by adrians5j** [comment]
Can you try running the same deploy command with `--debug` flag added?

**Comment by chrysos** [comment]
Hi @adrians5j, thanks for your interest.
I pasted from the error:

```
webiny success: Done! Deploy finished in 81.941s.

webiny info: Running "hook-after-deploy" hook...
webiny success: Hook "hook-after-deploy" completed.
webiny success: apps/api project application was deployed successfully!

webiny info: Deploying apps/admin project application...
^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2cwebiny success: Successfully loaded environment variables from /Users/samuelarendt/Code/webiny/.env.
webiny success: Successfully loaded environment variables from /Users/samuelarendt/Code/webiny/.env.dev.
webiny debug: No environment file found on /Users/samuelarendt/Code/webiny/apps/admin/.env.dev.
webiny debug: No environment file found on /Users/samuelarendt/Code/webiny/apps/admin/.env.
webiny info: Running "hook-before-build" hook...
webiny success: Hook "hook-before-build" completed.
webiny info: Building admin package...

ℹ Compiling Admin




webiny error: admin
(node:84249) Warning: Label 'JIT TOTAL' already exists for console.time()
(Use `node --trace-warnings ...` to show where the warning was created)


webiny error: Failed to build all packages (1 error occurred).
webiny debug:  Error: Failed to build all packages (1 error occurred).
    at module.exports (/Users/samuelarendt/Code/webiny/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy/buildPackages.js:167:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at command (/Users/samuelarendt/Code/webiny/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy.js:20:17)
    at Object.handler (/Users/samuelarendt/Code/webiny/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/index.js:61:21)

webiny error: Command failed with exit code 1: yarn webiny deploy apps/admin --env dev --debug true --build true --preview false
webiny debug:  Error: Command failed with exit code 1: yarn webiny deploy apps/admin --env dev --debug true --build true --preview false
    at makeError (/Users/samuelarendt/Code/webiny/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/samuelarendt/Code/webiny/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/Users/samuelarendt/Code/webiny/node_modules/@webiny/cwp-template-aws/cli/deploy/deploy.js:97:9)
    at async Object.handler (/Users/samuelarendt/Code/webiny/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/index.js:61:21) {
  shortMessage: 'Command failed with exit code 1: yarn webiny deploy apps/admin --env dev --debug true --build true --preview false',
  command: 'yarn webiny deploy apps/admin --env dev --debug true --build true --preview false',
  escapedCommand: 'yarn webiny deploy "apps/admin" --env dev --debug true --build true --preview false',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
