### ISSUE TITLE
Can't deploy project after first installation

### ISSUE THREAD

**Issue by limesquare-nl** [webiny/webiny-js#3144]
### Version

5.34.7

### Operating System

Ubuntu 22.04.2 LTS

### Browser

CLI

### What are the steps to reproduce this bug?

npx create-webiny-project project-name
cd project-name
yarn webiny login <login_id> or yarn webiny deploy

### What is the expected behavior?

Project deployed

### What do you see instead?

Internal Error: Assertion failed: Expected workspace admin (/home/forge/project-name/apps/admin/package.json) to have been resolved. Run "yarn install" to update the lockfile
    at je.refreshWorkspaceDependencies (/home/forge/project-name/.yarn/releases/yarn-3.5.0.cjs:439:3768)
    at je.restoreInstallState (/home/forge/project-name/.yarn/releases/yarn-3.5.0.cjs:445:1228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Pu.execute (/home/forge/project-name/.yarn/releases/yarn-3.5.0.cjs:572:1842)
    at async Pu.validateAndExecute (/home/forge/project-name/.yarn/releases/yarn-3.5.0.cjs:345:664)
    at async Un.run (/home/forge/project-name/.yarn/releases/yarn-3.5.0.cjs:359:2057)
    at async Ym.execute (/home/forge/project-name/.yarn/releases/yarn-3.5.0.cjs:472:509)
    at async Ym.validateAndExecute (/home/forge/project-name/.yarn/releases/yarn-3.5.0.cjs:345:664)
    at async Un.run (/home/forge/project-name/.yarn/releases/yarn-3.5.0.cjs:359:2057)
    at async Un.runExit (/home/forge/project-name/.yarn/releases/yarn-3.5.0.cjs:359:2241)

**Comment by remifreriks** [comment]
You can close this issue. I solved it by installing webiny on my local computer. Are you dependent on your local computer if you want to work on projects or is it also possible to run a project in Amazon Cloud 9?
