### ISSUE TITLE
yarn webiny deploy fails

### ISSUE THREAD

**Issue by ile** [webiny/webiny-js#3168]
### Version

5.34.7

### Operating System

Ubuntu 22.04.2

### What are the steps to reproduce this bug?

in `~/.aws/credentials` I have

```
[webiny]
aws_access_key_id = removed
aws_secret_access_key = removed
```

Running:

```
$ npx create-webiny-project test1
$ cd test1
$ cp ../.env .
$ cat .env
AWS_PROFILE=webiny
ile@ile-pc:/media/ile/Data2/src/webiny/test1$ yarn webiny deploy
It looks like this is your first time using @webiny/pulumi-sdk.
✔ Pulumi downloaded, continuing...
[resource plugin aws-5.34.0] installing
Downloading plugin: 155.16 MiB / 155.16 MiB [======================] 100.00% 26s

webiny info: This is your first time deploying the project (dev environment). Note that the initial deployment can take up to 15 minutes, so please be patient.

webiny info: Deploying core project application...
webiny info: Running "hook-before-build" hook...
webiny success: Hook "hook-before-build" completed.
webiny info: No packages to build...
webiny info: Running "hook-after-build" hook...
webiny success: Hook "hook-after-build" completed.

webiny error: Command failed with exit code 255: /media/ile/Data2/src/webiny/test1/.webiny/pulumi-cli/linux/pulumi/pulumi stack select dev --create --non-interactive
error: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables
Created stack 'dev'
webiny debug:  Error: Command failed with exit code 255: /media/ile/Data2/src/webiny/test1/.webiny/pulumi-cli/linux/pulumi/pulumi stack select dev --create --non-interactive
error: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables
Created stack 'dev'
    at makeError (/media/ile/Data2/src/webiny/test1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/media/ile/Data2/src/webiny/test1/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at command (/media/ile/Data2/src/webiny/test1/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy.js:43:13)
    at Object.handler (/media/ile/Data2/src/webiny/test1/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/index.js:63:21) {
  shortMessage: 'Command failed with exit code 255: /media/ile/Data2/src/webiny/test1/.webiny/pulumi-cli/linux/pulumi/pulumi stack select dev --create --non-interactive',
  command: '/media/ile/Data2/src/webiny/test1/.webiny/pulumi-cli/linux/pulumi/pulumi stack select dev --create --non-interactive',
  escapedCommand: '"/media/ile/Data2/src/webiny/test1/.webiny/pulumi-cli/linux/pulumi/pulumi" stack select dev --create --non-interactive',
  exitCode: 255,
  signal: undefined,
  signalDescription: undefined,
  stdout: "Created stack 'dev'",
  stderr: 'error: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

webiny error: Command failed with exit code 1: yarn webiny deploy apps/core --env dev --debug false --build true --preview false
```

**Comment by ile** [comment]
Using `.example.env` got it done.
