### ISSUE TITLE
Eslint prevents deployment of fresh install- Failed to compile: [eslint] Cannot read property 'getTokens' of undefined

### ISSUE THREAD

**Issue by larissa-n** [webiny/webiny-js#3291]
### Version

Latest

### What are the steps to reproduce this bug?

Fresh install, follow "getting started" guide

### What do you see instead?

```
webiny info: Deploying apps/admin project application...
webiny info: Running "hook-before-build" hook...
webiny success: Hook "hook-before-build" completed.
webiny info: Building admin package...

ℹ Compiling Admin
✔ Admin: Compiled with some errors in 1.77m
[eslint] Cannot read property 'getTokens' of undefined
Occurred while linting /Users/.../webiny-project/apps/admin/src/App.tsx:6
Rule: "@typescript-eslint/no-empty-function"
Failed to compile.

[eslint] Cannot read property 'getTokens' of undefined
Occurred while linting /Users/.../webiny-project/apps/admin/src/App.tsx:6
Rule: "@typescript-eslint/no-empty-function"

webiny error: An error occurred while building admin package.

webiny error: Failed to build all packages (1 error occurred).
webiny debug:  Error: Failed to build all packages (1 error occurred).
    at module.exports (/Users/.../webiny-project/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy/buildPackages.js:167:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at command (/Users/.../webiny-project/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy.js:20:17)
    at Object.handler (/Users/.../webiny-project/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/index.js:63:21)

webiny error: Command failed with exit code 1: yarn webiny deploy apps/admin --env dev --debug false --build true --preview false
```

### Additional information

@swapnilmmane also ran into this (thanks for pointing me toward [`yarn webiny destroy`](https://www.webiny.com/docs/infrastructure/basics/destroy-cloud-infrastructure) for cleanup after failed installs!)
Also thanks to @adrians5j !

### Possible solution

Add:
```
"@typescript-eslint/no-empty-function": 0,
```
to `.esintrc.js` rules.

**Comment by adrians5j** [comment]
Still looking into this, hold on!

**Comment by adrians5j** [comment]
Found it, it was because two diff versions of `eslint`were included in user's projects.

Just add this into your root package.json file, and should fix this:

![image](https://github.com/webiny/webiny-js/assets/5121148/75e7a22f-1f1f-4205-8497-5e1755754d95)


The whole `resolutions` object:

```
	"resolutions": {
		"eslint": "8.40.0", // Add this line
		"@emotion/react": "11.10.8",
		"@types/react": "17.0.39",
		"react": "17.0.2",
		"typescript": "4.7.4",
		"react-dom": "17.0.2",
		"codex-tooltip": "1.0.2"
	}
```

We'll address this for 5.35.1 soon.

**Comment by johnemcbride** [comment]
First timer here, just tried to run this today... same issue.   Applied the above fix, but still get:

```

ℹ Compiling Admin
✔ Admin: Compiled with some errors in 51.33s
[eslint] Cannot read properties of undefined (reading 'getTokens')
Occurred while linting /Users/johnmcbride/projects/bandmanager/apps/admin/src/App.tsx:6
Rule: "@typescript-eslint/no-empty-function"
Failed to compile.

[eslint] Cannot read properties of undefined (reading 'getTokens')
Occurred while linting /Users/johnmcbride/projects/bandmanager/apps/admin/src/App.tsx:6
Rule: "@typescript-eslint/no-empty-function"

webiny error: An error occurred while building admin package.

webiny error: Failed to build all packages (1 error occurred).
webiny debug:  Error: Failed to build all packages (1 error occurred).
    at module.exports (/Users/johnmcbride/projects/bandmanager/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy/buildPackages.js:167:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at command (/Users/johnmcbride/projects/bandmanager/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/deploy.js:20:17)
    at Object.handler (/Users/johnmcbride/projects/bandmanager/node_modules/@webiny/cli-plugin-deploy-pulumi/commands/index.js:63:21)

webiny error: Command failed with exit code 1: yarn webiny deploy apps/admin --env dev --debug false --build true --preview false
```

**Comment by johnemcbride** [comment]
my package.json:

```
	"resolutions": {
		"eslint": "8.40.0",
		"@emotion/react": "11.10.8",
		"@types/react": "17.0.39",
		"react": "17.0.2",
		"typescript": "4.7.4",
		"react-dom": "17.0.2",
		"codex-tooltip": "1.0.2"
	}
}

**Comment by adrians5j** [comment]
Did you run `yarn` after setting the resolutions?

**Comment by johnemcbride** [comment]
cool, I cloned to a new folder with the change in package.json and did a fresh yarn deploy and it worked.  
Resolved an initial thing about copying the .env file across.
Noticed it has created a completely new stack so now I have two of everything.  
If I check the repo out and redeploy do I always get a new stack?

**Comment by larissa-n** [comment]
@johnemcbride Yes, a new project will randomly generate resource names, and those will come on top of what you have on AWS. Run the following to clean up a failed install (if you still have the project): https://www.webiny.com/docs/infrastructure/basics/destroy-cloud-infrastructure

**Comment by adrians5j** [comment]
Closing this as there's a workaround, plus we've went with a new dependencies locking approach in [5.35.1](https://www.webiny.com/docs/release-notes/5.35.1/changelog#lock-user-project-dependencies-3301).
