### ISSUE TITLE
Error updating to 5.39.x from 5.38.x. TypeError: LRU is not a constructor

### ISSUE THREAD

**Issue by agnihotrish** [webiny/webiny-js#4160]
### Version

5.38.0

### Operating System

Mac OS 14.5

### Browser

Chrome

### What are the steps to reproduce this bug?

Run yarn up "@webiny/*@5.39.6"  
Run yarn webiny upgrade

### What is the expected behavior?

Successful upgrade

### What do you see instead?

/Users/agnihotrish/Desktop/Development/webiny-demo/node_modules/@webiny/cli-plugin-deploy-pulumi/node_modules/semver/classes/range.js:199
const cache = new LRU({ max: 1000 })
              ^

TypeError: LRU is not a constructor
    at Object.<anonymous> (/Users/agnihotrish/Desktop/Development/webiny-demo/node_modules/@webiny/cli-plugin-deploy-pulumi/node_modules/semver/classes/range.js:199:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/agnihotrish/Desktop/Development/webiny-demo/node_modules/@webiny/cli-plugin-deploy-pulumi/node_modules/semver/classes/comparator.js:140:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

**Comment by agnihotrish** [comment]
Deleting node_modules folder worked.
