### ISSUE TITLE
Stuck on Installing Dependencies

### ISSUE THREAD

**Issue by boreendesign** [webiny/webiny-js#651]
I am trying to install webiny for the first time but I keep getting stuck on installing dependencies as below, I have to manually stop it.

My Details
Mac
Node Version : 12.14
Yarn install : 0.27.5
```
Webiny collects anonymous usage analytics to help improve the developer experience.
If you'd like to opt-out run webiny disable-tracking.
To learn more, check out https://www.webiny.com/telemetry/.

📦 Creating a new Webiny project in [REMOVED FOR SCREENSHOT]...
✔ Finished loading package versions
⠹ Installing dependencies...(node:47739) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1 (EPERM): yarn
    at makeError (/usr/local/lib/node_modules/@webiny/cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/@webiny/cli/node_modules/execa/index.js:112:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/usr/local/lib/node_modules/@webiny/cli/create/index.js:124:5)
(node:47739) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:47739) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠏ Installing dependencies...
```

**Comment by doitadrian** [comment]
Hi @boreendesign, thanks for the report.

Can you please tell me the following...
1) Which OS version you have?
2) Can you please check the version of Yarn, you stated `0.27.5`, but current stable version is `v1.21.1`. 

Thank you!

**Comment by boreendesign** [comment]
My apologies, I thought I had updated Yarn globally, I checked again and indeed I had not and now that its updated its installing, thank you.

**Comment by doitadrian** [comment]
Awesome!
